package com.benben.kupaizhibo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.benben.kupaizhibo.bean.ErrorMsg;

import com.benben.kupaizhibo.db.ErrorMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig errorMsgDaoConfig;

    private final ErrorMsgDao errorMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        errorMsgDaoConfig = daoConfigMap.get(ErrorMsgDao.class).clone();
        errorMsgDaoConfig.initIdentityScope(type);

        errorMsgDao = new ErrorMsgDao(errorMsgDaoConfig, this);

        registerDao(ErrorMsg.class, errorMsgDao);
    }
    
    public void clear() {
        errorMsgDaoConfig.clearIdentityScope();
    }

    public ErrorMsgDao getErrorMsgDao() {
        return errorMsgDao;
    }

}
